/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/avatar.glb -t -r public
*/

import * as THREE from "three";
import { clone as cloneSkinnedScene } from "three/addons/utils/SkeletonUtils.js";
import React, {
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import {
  useFrame,
  useGraph,
  useThree,
  type ThreeElements,
} from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

import { extendGltfLoaderBufferViewTextureFix } from "@/lib/gltf-buffer-view-texture-fix";
import type { Hero3dSettings } from "../../../site.config";
import { siteConfig } from "../../../site.config";

import type { ModelLayoutProps } from "./hero-framing";

export type { ModelLayoutProps } from "./hero-framing";

/** Stable decode path; bufferView blob textures use fixed revoke (see lib). */
useGLTF.preload("/avatar.glb", false, false, extendGltfLoaderBufferViewTextureFix);

type AvatarGraph = {
  nodes: {
    Ch36: THREE.SkinnedMesh;
    mixamorig1_Hips: THREE.Bone;
    mixamorig1_Neck: THREE.Bone;
    mixamorig1_Head: THREE.Bone;
    mixamorig1_LeftArm: THREE.Bone;
    mixamorig1_LeftForeArm: THREE.Bone;
    mixamorig1_RightArm: THREE.Bone;
    mixamorig1_RightForeArm: THREE.Bone;
    mixamorig1_LeftHandIndex1?: THREE.Bone;
    mixamorig1_LeftHandIndex2?: THREE.Bone;
  };
};

type BoneKey =
  | "mixamorig1_LeftArm"
  | "mixamorig1_LeftForeArm"
  | "mixamorig1_RightArm"
  | "mixamorig1_RightForeArm";

/**
 * Cached bind-pose quaternions per cloned scene so remounts / HMR do not
 * compound rotations on the same skeleton instance.
 */
const sceneBindQuaternions = new WeakMap<
  THREE.Object3D,
  Record<BoneKey, THREE.Quaternion>
>();

/** Bind poses for pointer-driven finger bones (relative to posed arms after layout). */
const sceneIndexFingerBind = new WeakMap<
  THREE.Object3D,
  {
    index1: THREE.Quaternion;
    index2: THREE.Quaternion;
    seeded: boolean;
  }
>();

/** Mixamo / glTF: local rotation applied as bind * delta (XYZ order for deltas only). */
const EULER_ORDER = "XYZ" as const;

/** Degrees — left arm raised ~45° “pointing” stance */
const LEFT_SHOULDER_PITCH_DEG = 100;
const LEFT_SHOULDER_ROLL_DEG = 50;
const LEFT_ELBOW_FLEX_DEG = 100;
/** Right arm lowered from T-pose — pitch + roll + bent elbow */
const RIGHT_SHOULDER_PITCH_DEG = 74;
const RIGHT_SHOULDER_ROLL_DEG = -24;
const RIGHT_ELBOW_FLEX_DEG = 20;

/** Inner hero group scale (matches JSX); light follow divides by this */
const INNER_HERO_SCALE = 2;

const scratchEuler = new THREE.Euler(0, 0, 0, EULER_ORDER);
const scratchQuat = new THREE.Quaternion();
const scratchTarget = new THREE.Vector3();
const scratchForward = new THREE.Vector3();
const scratchCamToTarget = new THREE.Vector3();
const scratchFingerTarget = new THREE.Quaternion();

type ModelProps = ThreeElements["group"] &
  ModelLayoutProps & {
    interaction?: Hero3dSettings;
  };

export function Model({
  layoutOffset,
  rotationY = 0,
  fitTarget = 0.9,
  innerGroupPosition = [0, -1.5, 0],
  framingTarget,
  interaction = siteConfig.hero3d,
  ...groupProps
}: ModelProps) {
  const { camera, size } = useThree();
  const lightRef = useRef<THREE.PointLight>(null);
  const headRef = useRef<THREE.Object3D | null>(null);
  const neckRef = useRef<THREE.Object3D | null>(null);
  const leftIndex1Ref = useRef<THREE.Object3D | null>(null);
  const leftIndex2Ref = useRef<THREE.Object3D | null>(null);
  const [meshHovered, setMeshHovered] = useState(false);
  /** No animation clips in avatar.glb — cursor response uses procedural bone lerp in useFrame */
  const { scene: cachedScene } = useGLTF(
    "/avatar.glb",
    false,
    false,
    extendGltfLoaderBufferViewTextureFix,
  );
  const scene = useMemo(
    () => cloneSkinnedScene(cachedScene),
    [cachedScene],
  );
  const { nodes } = useGraph(scene) as unknown as AvatarGraph;

  const bounds = useMemo(() => {
    const geometry = nodes.Ch36.geometry;
    geometry.computeBoundingBox();
    const bbox = geometry.boundingBox;
    if (!bbox) return null;
    const boxSize = bbox.getSize(new THREE.Vector3());
    const boxCenter = bbox.getCenter(new THREE.Vector3());
    return { boxSize, boxCenter };
  }, [nodes]);

  const modelScale = useMemo(() => {
    if (!bounds) return 1;

    const aspect = size.width / Math.max(size.height, 1);
    const perspective = camera as THREE.PerspectiveCamera;

    let depthAlongView: number;
    if (framingTarget) {
      scratchTarget.set(
        framingTarget[0],
        framingTarget[1],
        framingTarget[2],
      );
      camera.getWorldDirection(scratchForward);
      const projected = scratchCamToTarget
        .copy(scratchTarget)
        .sub(camera.position)
        .dot(scratchForward);
      depthAlongView = Math.max(projected, 0.08);
    } else {
      depthAlongView = Math.max(camera.position.length(), 0.08);
    }

    const visibleHeight =
      2 *
      depthAlongView *
      Math.tan(THREE.MathUtils.degToRad(perspective.fov) / 2);
    const visibleWidth = visibleHeight * aspect;

    const scaleX =
      (visibleWidth * fitTarget) / Math.max(bounds.boxSize.x, 1e-6);
    const scaleY =
      (visibleHeight * fitTarget) / Math.max(bounds.boxSize.y, 1e-6);

    return Math.min(Math.max(Math.min(scaleX, scaleY), 0.0001), 100);
  }, [bounds, camera, fitTarget, framingTarget, size.height, size.width]);

  /** Centering only — layoutOffset lives under scale so resize keeps composition stable */
  const modelPosition = useMemo(() => {
    if (!bounds) return new THREE.Vector3(0, 0, 0);
    return bounds.boxCenter.clone().multiplyScalar(-modelScale);
  }, [bounds, modelScale]);

  const layoutGroupPosition = layoutOffset ?? ([0, 0, 0] as const);

  // Ch36 and mixamorig1_Hips are siblings under FBX_Root — no duplicate mesh under Hips.
  // Head/neck must come from `nodes`: <primitive object={Hips}> reparents the armature off `scene`,
  // so scene.getObjectByName("mixamorig1_Head") stays null and head tracking silently breaks.
  useLayoutEffect(() => {
    const byName = (name: string) =>
      (nodes as Record<string, THREE.Object3D | undefined>)[name] ??
      nodes.mixamorig1_Hips.getObjectByName(name);

    headRef.current = nodes.mixamorig1_Head;
    neckRef.current = nodes.mixamorig1_Neck;
    leftIndex1Ref.current =
      byName("mixamorig1_LeftHandIndex1") ?? null;
    leftIndex2Ref.current =
      byName("mixamorig1_LeftHandIndex2") ?? null;
    if (headRef.current) {
      headRef.current.rotation.order = EULER_ORDER;
    }
    if (neckRef.current) {
      neckRef.current.rotation.order = EULER_ORDER;
    }
    if (leftIndex1Ref.current) {
      leftIndex1Ref.current.rotation.order = EULER_ORDER;
    }
    if (leftIndex2Ref.current) {
      leftIndex2Ref.current.rotation.order = EULER_ORDER;
    }

    let fingerBind = sceneIndexFingerBind.get(scene);
    if (!fingerBind) {
      fingerBind = {
        index1: new THREE.Quaternion(),
        index2: new THREE.Quaternion(),
        seeded: false,
      };
      sceneIndexFingerBind.set(scene, fingerBind);
    }
    if (
      !fingerBind.seeded &&
      leftIndex1Ref.current &&
      leftIndex2Ref.current
    ) {
      fingerBind.index1.copy(leftIndex1Ref.current.quaternion);
      fingerBind.index2.copy(leftIndex2Ref.current.quaternion);
      fingerBind.seeded = true;
    } else if (!fingerBind.seeded && leftIndex1Ref.current) {
      fingerBind.index1.copy(leftIndex1Ref.current.quaternion);
      fingerBind.seeded = true;
    }

    let bind = sceneBindQuaternions.get(scene);
    if (!bind) {
      bind = {
        mixamorig1_LeftArm: nodes.mixamorig1_LeftArm.quaternion.clone(),
        mixamorig1_LeftForeArm: nodes.mixamorig1_LeftForeArm.quaternion.clone(),
        mixamorig1_RightArm: nodes.mixamorig1_RightArm.quaternion.clone(),
        mixamorig1_RightForeArm:
          nodes.mixamorig1_RightForeArm.quaternion.clone(),
      };
      sceneBindQuaternions.set(scene, bind);
    }

    scratchEuler.set(
      THREE.MathUtils.degToRad(LEFT_SHOULDER_PITCH_DEG),
      0,
      THREE.MathUtils.degToRad(LEFT_SHOULDER_ROLL_DEG),
      EULER_ORDER,
    );
    scratchQuat.setFromEuler(scratchEuler);
    nodes.mixamorig1_LeftArm.quaternion
      .copy(bind.mixamorig1_LeftArm)
      .multiply(scratchQuat);

    scratchEuler.set(
      THREE.MathUtils.degToRad(LEFT_ELBOW_FLEX_DEG),
      0,
      0,
      EULER_ORDER,
    );
    scratchQuat.setFromEuler(scratchEuler);
    nodes.mixamorig1_LeftForeArm.quaternion
      .copy(bind.mixamorig1_LeftForeArm)
      .multiply(scratchQuat);

    scratchEuler.set(
      THREE.MathUtils.degToRad(RIGHT_SHOULDER_PITCH_DEG),
      0,
      THREE.MathUtils.degToRad(RIGHT_SHOULDER_ROLL_DEG),
      EULER_ORDER,
    );
    scratchQuat.setFromEuler(scratchEuler);
    nodes.mixamorig1_RightArm.quaternion
      .copy(bind.mixamorig1_RightArm)
      .multiply(scratchQuat);

    scratchEuler.set(
      THREE.MathUtils.degToRad(RIGHT_ELBOW_FLEX_DEG),
      0,
      0,
      EULER_ORDER,
    );
    scratchQuat.setFromEuler(scratchEuler);
    nodes.mixamorig1_RightForeArm.quaternion
      .copy(bind.mixamorig1_RightForeArm)
      .multiply(scratchQuat);

    nodes.mixamorig1_LeftArm.updateMatrixWorld(true);
    nodes.mixamorig1_RightArm.updateMatrixWorld(true);
  }, [scene, nodes]);

  useFrame((state) => {
    const delta = state.clock.getDelta();
    const ht = interaction.headTracking;
    const t = Math.min(ht.lerpSpeed * delta, 1);
    const { pointer } = state;

    if (ht.enabled) {
      const targetY = THREE.MathUtils.clamp(
        pointer.x * ht.maxYawRad,
        -ht.maxYawRad,
        ht.maxYawRad,
      );
      const targetX = THREE.MathUtils.clamp(
        pointer.y * ht.maxPitchRad,
        ht.pitchClampMin,
        ht.pitchClampMax,
      );

      const head = headRef.current;
      if (head) {
        head.rotation.x = THREE.MathUtils.lerp(head.rotation.x, targetX, t);
        head.rotation.y = THREE.MathUtils.lerp(head.rotation.y, targetY, t);
      }

      const neckYaw = ht.maxYawRad * ht.neckYawScale;
      const neckPitch = ht.maxPitchRad * ht.neckPitchScale;
      const neckPitchMin = ht.pitchClampMin * ht.neckPitchClampScale;
      const neckPitchMax = ht.pitchClampMax * ht.neckPitchClampScale;

      const neck = neckRef.current;
      if (neck) {
        const nY = THREE.MathUtils.clamp(
          pointer.x * neckYaw,
          -neckYaw,
          neckYaw,
        );
        const nX = THREE.MathUtils.clamp(
          pointer.y * neckPitch,
          neckPitchMin,
          neckPitchMax,
        );
        neck.rotation.x = THREE.MathUtils.lerp(neck.rotation.x, nX, t);
        neck.rotation.y = THREE.MathUtils.lerp(neck.rotation.y, nY, t);
      }
    }

    const pf = interaction.pointerFinger;
    if (pf.enabled) {
      const fingerBind = sceneIndexFingerBind.get(scene);
      const ft = Math.min(pf.lerpSpeed * delta, 1);
      const idx1 = leftIndex1Ref.current;
      const idx2 = leftIndex2Ref.current;
      if (fingerBind && idx1) {
        const yaw = THREE.MathUtils.clamp(
          pointer.x * pf.maxYawRad,
          -pf.maxYawRad,
          pf.maxYawRad,
        );
        const pitch = THREE.MathUtils.clamp(
          pointer.y * pf.maxPitchRad,
          pf.pitchClampMin,
          pf.pitchClampMax,
        );
        scratchEuler.set(pitch, yaw, 0, EULER_ORDER);
        scratchQuat.setFromEuler(scratchEuler);
        scratchFingerTarget.copy(fingerBind.index1).multiply(scratchQuat);
        idx1.quaternion.slerp(scratchFingerTarget, ft);

        if (idx2) {
          scratchEuler.set(pitch * pf.index2PitchScale, 0, 0, EULER_ORDER);
          scratchQuat.setFromEuler(scratchEuler);
          scratchFingerTarget.copy(fingerBind.index2).multiply(scratchQuat);
          idx2.quaternion.slerp(scratchFingerTarget, ft);
        }
      }
    }

    if (!lightRef.current || !interaction.lightFollow.enabled) return;
    const lf = interaction.lightFollow;
    const lightScale = modelScale / INNER_HERO_SCALE;
    lightRef.current.position.set(
      pointer.x * lf.xy * lightScale,
      pointer.y * lf.xy * lightScale,
      lf.z * lightScale,
    );
  });

  return (
    <group
      {...groupProps}
      position={modelPosition}
      rotation={[0, rotationY, 0]}
      scale={modelScale}
      dispose={null}
    >
      <group
        position={[
          layoutGroupPosition[0],
          layoutGroupPosition[1],
          layoutGroupPosition[2],
        ]}
      >
        <group
          position={[
            innerGroupPosition[0],
            innerGroupPosition[1],
            innerGroupPosition[2],
          ]}
          scale={INNER_HERO_SCALE}
        >
          <pointLight
            ref={lightRef}
            color="#ccff00"
            intensity={10}
            distance={5}
          />
          <primitive object={nodes.mixamorig1_Hips} />
          <skinnedMesh
            geometry={nodes.Ch36.geometry}
            skeleton={nodes.Ch36.skeleton}
            onPointerOver={(e) => {
              if (!interaction.hoverHighlight.enabled) return;
              e.stopPropagation();
              setMeshHovered(true);
            }}
            onPointerOut={(e) => {
              if (!interaction.hoverHighlight.enabled) return;
              e.stopPropagation();
              setMeshHovered(false);
            }}
          >
            <meshPhysicalMaterial
              color="#2a2d35"
              metalness={1}
              roughness={0.15}
              clearcoat={1}
              envMapIntensity={1}
              emissive={interaction.hoverHighlight.emissive}
              emissiveIntensity={
                interaction.hoverHighlight.enabled && meshHovered
                  ? interaction.hoverHighlight.intensity
                  : 0
              }
            />
          </skinnedMesh>
        </group>
      </group>
    </group>
  );
}
